### ISSUE TITLE
mirror_mysql_database.py: error: the following arguments are required: source, target

### ISSUE THREAD

**Issue by z3rone** [mastersign/mysql-mirror#1]
I'm getting errors from the docker container that the mirror script requires the arguments `source` and `target`.

docker-compose.yml
```
services:
  attendance-db:
    image: mysql:8
    ports:
      - "127.0.0.10:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret_password
      - MYSQL_DATABASE=attendance
      - MYSQL_USER=attendance
      - MYSQL_PASSWORD=123123
  db-clone:
    image: mastersign/mysql-mirror
    volumes:
      - "./mysql-clone-config.init:/app/config.ini"
```
mysql-clone-config.init
```
[database.a]
host = db-nas:49186
schema = attendance
user = attendance
password = 123123

[database.b]
host = attendance-db:3306
schema = attendance
user = root
password = secret_password

[mirror.a.b]
drop_schema = yes
whole_schema = no
```

Start-up:
```
docker-compose up -d attendance-db
docker-compose up -d db-clone
docker-compose log db-clone
```
Output:
```
db-clone_1            | usage: mirror_mysql_database.py [-h] [-v] [-t TABLE] [-w] [-d]
db-clone_1            |                                 [-c CONFIG_FILES] [-o OPTIONS [OPTIONS ...]]
db-clone_1            |                                 source target
db-clone_1            | mirror_mysql_database.py: error: the following arguments are required: source, target
```

**Comment by z3rone** [comment]
My bad. I was missing the parameters:
```
  db-clone:
    image: mastersign/mysql-mirror
    volumes:
      - "./mysql-clone-config.init:/app/config.ini"
    command:
      - "a"
      - "b"
```
